version: "3"

services:
  cafe:
    container_name: cafe
    build:
      context: .
      dockerfile: ./apps/cafe/Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - app_network
  todo:
    container_name: todo
    build:
      context: .
      dockerfile: ./apps/todo/Dockerfile
    restart: always
    ports:
      - 3001:3001
    networks:
      - app_network

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  app_network:
    external: true
